// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBvlpPAuVvFnKSrRmpHjFSQbCO5I4qMc',
    appId: '1:862524390346:web:801115777ecf337926ed33',
    messagingSenderId: '862524390346',
    projectId: 'blogging-platform-ba272',
    authDomain: 'blogging-platform-ba272.firebaseapp.com',
    storageBucket: 'blogging-platform-ba272.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdwLqobXTbRpnv_q59BOZcV5XoKHEtOI8',
    appId: '1:862524390346:android:ee2b2e9b45635cfe26ed33',
    messagingSenderId: '862524390346',
    projectId: 'blogging-platform-ba272',
    storageBucket: 'blogging-platform-ba272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0qp2vU9qV83GRiVP_Yeph_EY2mcQ-rkY',
    appId: '1:862524390346:ios:e9f08c41c201f55b26ed33',
    messagingSenderId: '862524390346',
    projectId: 'blogging-platform-ba272',
    storageBucket: 'blogging-platform-ba272.firebasestorage.app',
    iosBundleId: 'com.example.newapp123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0qp2vU9qV83GRiVP_Yeph_EY2mcQ-rkY',
    appId: '1:862524390346:ios:e9f08c41c201f55b26ed33',
    messagingSenderId: '862524390346',
    projectId: 'blogging-platform-ba272',
    storageBucket: 'blogging-platform-ba272.firebasestorage.app',
    iosBundleId: 'com.example.newapp123',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiBvlpPAuVvFnKSrRmpHjFSQbCO5I4qMc',
    appId: '1:862524390346:web:c18d8a607543454326ed33',
    messagingSenderId: '862524390346',
    projectId: 'blogging-platform-ba272',
    authDomain: 'blogging-platform-ba272.firebaseapp.com',
    storageBucket: 'blogging-platform-ba272.firebasestorage.app',
  );
}
